collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

excerpt_length: 100
excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag